name: test_package

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  package_test__orders_reference: "int_orders"
  package_test__orders_available: false