name: test_package_integration_test
profile: dbt_fusion_test

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  package_test__orders_reference: "seed_orders"
  package_test__orders_available: true